macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

build_task:
  name: Build

  env:
    PATH: ${HOME}/.local/bin:${PATH}

  python_script:
    - brew update
    - brew install python@3.10
    - ln -s python3 /opt/homebrew/opt/python@3.10/bin/python

  poetry_script:
    - curl -sSL https://install.python-poetry.org | python3 -
    - poetry config experimental.new-installer false
    - poetry config virtualenvs.create true
    - poetry config virtualenvs.in-project true

  python_dependencies_script:
    - poetry install

  run_script:
    - source .venv/bin/activate
    - pyinstaller --noconfirm main.spec
    - dist/main.app/Contents/MacOS/main

  dist_artifacts:
    name: main
    paths:
      - dist/main.app
